chaos.proto
=> proto: manage wordings of cause

chaos.proto
=> proto: category added

chaos.proto
=> proto: Correction M to m in message

chaos.proto
Allows to add one or more enumereated types in a channel.
=> chaos-proto: A list of types added in a channel

chaos.proto
=> chaos-proto: push field added in impact

chaos.proto
Provider of th disruption added
=> chaos-proto: contributor added

chaos.proto
=> chaos-proto: extension of tripupdate added

kirin.proto
=> chaos-proto: contributor added in TripDescriptor

kirin.proto
the chaos Message in trip updates was not usefull, change it with a
simple string
=> add a cause to the stoptime and change tripupdate

chaos.proto, kirin.proto
@CanalTP/reseaulution could you check there is no problems with chaos?
This should not, our CI is still in 2.6 and we didn't encounter any problem
=> Specify syntax as proto2 for compatibity with protocolbuffer 3

chaos.proto
Related to old https://github.com/CanalTP/Chaos/pull/251 :older_man:
=> New channels

chaos.proto
Linked to PR : CanalTP/navitia#2257
=> adding disruption properties in chaos.proto

chaos.proto
Renaming properties as requested in PR : https://github.com/CanalTP/navitia/pull/2257
=> chaos: rename properties

kirin.proto
For details see: https://jira.kisio.org/browse/NAVP-1032
=> chaos-proto: company added in TripUpdate as extension

kirin.proto
https://jira.kisio.org/browse/NAVP-1080
=> chaos-proto: exension Effect added in TripUpdate

kirin.proto
Add status for new use cases around detour:
- Skip for detour
- Added for detour
https://jira.kisio.org/browse/NAVP-1082
=> Add new enum to define Stop time event status with the new usecases

kirin.proto
Since it's the first implementation, we don't risk anything changing it :)
=> Update naming for consistency

kirin.proto
https://jira.kisio.org/browse/NAVP-1063
=> Add an extension physical_mode_id in VehicleDescriptor

kirin.proto
https://jira.kisio.org/browse/NAVP-1069
=> Add an extension label in VehicleDescriptor

chaos.proto
This PR delete some entry on the line section part (no use)
Issue : BOT-1916
=> Update chaos.proto for line section

chaos.proto
We add pattern if used while creating impact so that we can also add it the response navitia.
Concerned ticket: https://jira.kisio.org/browse/NAVITIAII-3276
=> Proto: application pattern added

chaos.proto
To add ptobject type `rail_section` definition.
Relates to BOT-2418
=> New feature rail_section

chaos.proto
This pr add routes and remove route_pattern from rail_section
bot-2626
related to: https://github.com/CanalTP/Chaos/pull/471
=> Rail_section add routes remove route_pattern

chaos.proto
Will be used by CHAOS & KRONOS
(related PR in progress)
=> Addition notification date in Message

kirin_proto_doc.rs
As discussed in https://github.com/CanalTP/loki/pull/94
Chaos-proto seems to be the best place to store this documentation
=> Documentation of kirin proto

chaos.proto
:warning: it's a breaking change as it concerns at least : Chaos, Loki & Navitia
cf https://github.com/search?q=org%3Ahove-io+unkown_type&type=code
edit : alias will allow smooth change between projects
=> [Wording] unknown resolution

chaos.proto
This PR add the translation part on the message proto
relates to https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#message-translation
BO-1318 / BO-1417
=> Add translation to message

kirin_proto_doc.rs
After https://github.com/hove-io/navitia/pull/3909#discussion_r1073528296
=> Doc: the last FeedEntity received for a given id is the one that matters

chaos.proto
patch #41 
relates to BO-1950
dependency > https://github.com/hove-io/Chaos/pull/607
=> bo-1950 [Chaos] url_audio in Message

kirin.proto
This will allow specifying targetted values for attributes instead of default values.
Related to SFD: https://navitia.atlassian.net/wiki/spaces/NAV/pages/7100538825/SFD+connecteur+SIRI-ET+XML+TN#TripUpdate
JIRA ticket: https://navitia.atlassian.net/browse/NAV-1926
=> Kirin (NTFSRT-TripUpdate): Add new attributes for trip creation

chaos.proto
=> [TR API Chaos] Impact ptobject type POI

chaos.proto
Add pids (Passenger Information Display System)
=> [BO-3729] - Add pids for channel types

kirin.proto
For more details: https://navitia.atlassian.net/browse/NAV-3872
=> [KIRIN]: Adding BoardingActivity attributes
